### ISSUE TITLE
Switch to new OpenAI Gym step API

### ISSUE THREAD

**Issue by xiaomengy** [facebookresearch/rlmeta#78]
The new version of OpenAI Gym uses a new step API which returns (observations, reward, termination, truncation, info) instead of (observations, reward, done, info). We have to make the wrappers to support this.

Track this progress in this issue.

**Comment by d3sm0** [comment]
Would this wrapper help? https://github.com/openai/gym/blob/master/gym/wrappers/step_api_compatibility.py
